include: package:sizzle_lints/lints.yaml
analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    for_in_of_invalid_type: warning
    inference_failure_on_instance_creation: info
    invalid_assignment: error
    non_bool_condition: warning
    parameter_assignments: info
    # use_build_context_synchronously: ignore
    avoid_setters_without_getters: ignore
    flutter_style_todos: ignore
    argument_type_not_assignable: error
    depend_on_referenced_packages: error
    inference_failure_on_untyped_parameter: error

  exclude:
    - "lib/src/core/localization/generated/**"
    - "**/*.g.dart"
    - "**/generated/**"
dart_code_metrics:
  extends:
    - package:sizzle_lints/dcm.yaml
  rules:
    avoid-unassigned-late-fields: info
    avoid-missing-image-alt: false
    avoid-unused-parameters: info
    move-variable-closer-to-its-usage: info
    avoid-throw-in-catch-block: error
    avoid-empty-setstate: info
    no-empty-block: info
    avoid-unnecessary-reassignment: info
    use-setstate-synchronously: info
    avoid-undisposed-instances: error
    dispose-fields: error
    avoid-passing-self-as-argument: ignore
    avoid-dynamic: info
