// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGaiYFveXnwbag-ORPYbsV6m3XuWsX1jk',
    appId: '1:66812962587:android:f03afe9f66caf284e655be',
    messagingSenderId: '66812962587',
    projectId: 'sailingchefs-3e3cb',
    storageBucket: 'sailingchefs-3e3cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpzT46q83H88YZxaX32aLZyHECfdRfZdQ',
    appId: '1:66812962587:ios:9e68ed6e74ad4d83e655be',
    messagingSenderId: '66812962587',
    projectId: 'sailingchefs-3e3cb',
    storageBucket: 'sailingchefs-3e3cb.appspot.com',
    androidClientId: '66812962587-1urft5vf5ho831et6t37vlldhbrf7rud.apps.googleusercontent.com',
    iosClientId: '66812962587-1melobgoo2n16rbnukfsu3qcfvpeo7um.apps.googleusercontent.com',
    iosBundleId: 'com.drudotstech.SailingChefs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUleuxvhTvY6GIow7h6JLMnW1XapaejyQ',
    appId: '1:66812962587:web:abafa323691e4a45e655be',
    messagingSenderId: '66812962587',
    projectId: 'sailingchefs-3e3cb',
    authDomain: 'sailingchefs-3e3cb.firebaseapp.com',
    storageBucket: 'sailingchefs-3e3cb.appspot.com',
    measurementId: 'G-EEH9TH82Q1',
  );

}