// Mocks generated by Mockito 5.4.4 from annotations
// in sailing_chefs/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i23;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i6;
import 'package:geolocator/geolocator.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sailing_chefs/model/comment_model.dart' as _i22;
import 'package:sailing_chefs/model/conversation_model.dart' as _i14;
import 'package:sailing_chefs/model/dish_model.dart' as _i19;
import 'package:sailing_chefs/model/message_model.dart' as _i15;
import 'package:sailing_chefs/model/recipe_model.dart' as _i10;
import 'package:sailing_chefs/model/user_model.dart' as _i17;
import 'package:sailing_chefs/services/chef_service.dart' as _i16;
import 'package:sailing_chefs/services/comment_service.dart' as _i21;
import 'package:sailing_chefs/services/conversation_service.dart' as _i13;
import 'package:sailing_chefs/services/dishes_service.dart' as _i18;
import 'package:sailing_chefs/services/location_service.dart' as _i12;
import 'package:sailing_chefs/services/recipe_service.dart' as _i9;
import 'package:sailing_chefs/services/saved_recipe_service.dart' as _i24;
import 'package:sailing_chefs/services/user_services.dart' as _i3;
import 'package:sailing_chefs/services/userdata_service_service.dart' as _i20;
import 'package:stacked_services/stacked_services.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserServices_1 extends _i1.SmartFake implements _i3.UserServices {
  _FakeUserServices_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i4.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i6.GlobalKey<_i6.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i6.GlobalKey<_i6.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i4.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<T?>? navigateWithTransition<T>(
    _i6.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i6.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i4.Transition? transitionClass,
    _i4.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? replaceWithTransition<T>(
    _i6.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i6.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i4.Transition? transitionClass,
    _i4.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i6.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i6.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? navigateToView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i6.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i4.Transition? transition,
    _i4.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i6.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearStackAndShowView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? clearTillFirstAndShowView<T>(
    _i6.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);

  @override
  _i7.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i6.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i7.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i4.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i4.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i7.Future<_i4.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i7.Future<_i4.SheetResponse<dynamic>?>.value(),
      ) as _i7.Future<_i4.SheetResponse<dynamic>?>);

  @override
  _i7.Future<_i4.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i8.Color? barrierColor = const _i8.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i7.Future<_i4.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i7.Future<_i4.SheetResponse<T>?>.value(),
      ) as _i7.Future<_i4.SheetResponse<T>?>);

  @override
  void completeSheet(_i4.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i4.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i4.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i6.Widget Function(
      _i6.BuildContext,
      _i4.DialogRequest<dynamic>,
      dynamic Function(_i4.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i8.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i8.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i4.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
      ) as _i7.Future<_i4.DialogResponse<dynamic>?>);

  @override
  _i7.Future<_i4.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i8.Color? barrierColor = const _i8.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i7.Future<_i4.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i7.Future<_i4.DialogResponse<T>?>.value(),
      ) as _i7.Future<_i4.DialogResponse<T>?>);

  @override
  _i7.Future<_i4.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i8.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i8.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i4.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i7.Future<_i4.DialogResponse<dynamic>?>.value(),
      ) as _i7.Future<_i4.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i4.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RecipeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeService extends _i1.Mock implements _i9.RecipeService {
  @override
  _i7.Future<bool> addRecipeToFirestore(_i10.RecipeModel? recipe) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecipeToFirestore,
          [recipe],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> uploadImagesToFirebase(List<_i11.XFile?>? images) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImagesToFirebase,
          [images],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i10.RecipeModel>> fetchRecipesByUID(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRecipesByUID,
          [uid],
        ),
        returnValue:
            _i7.Future<List<_i10.RecipeModel>>.value(<_i10.RecipeModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i10.RecipeModel>>.value(<_i10.RecipeModel>[]),
      ) as _i7.Future<List<_i10.RecipeModel>>);

  @override
  _i7.Future<List<_i10.RecipeModel>> fetchAllRecipes() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllRecipes,
          [],
        ),
        returnValue:
            _i7.Future<List<_i10.RecipeModel>>.value(<_i10.RecipeModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i10.RecipeModel>>.value(<_i10.RecipeModel>[]),
      ) as _i7.Future<List<_i10.RecipeModel>>);

  @override
  _i7.Future<List<_i10.RecipeModel>> fetchRandomRecipes(int? count) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRandomRecipes,
          [count],
        ),
        returnValue:
            _i7.Future<List<_i10.RecipeModel>>.value(<_i10.RecipeModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i10.RecipeModel>>.value(<_i10.RecipeModel>[]),
      ) as _i7.Future<List<_i10.RecipeModel>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i12.LocationService {
  @override
  _i7.Future<_i2.Position> determinePosition() => (super.noSuchMethod(
        Invocation.method(
          #determinePosition,
          [],
        ),
        returnValue: _i7.Future<_i2.Position>.value(_FakePosition_0(
          this,
          Invocation.method(
            #determinePosition,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Position>.value(_FakePosition_0(
          this,
          Invocation.method(
            #determinePosition,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Position>);
}

/// A class which mocks [ConversationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationService extends _i1.Mock
    implements _i13.ConversationService {
  @override
  String get currentUserUid => (super.noSuchMethod(
        Invocation.getter(#currentUserUid),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentUserUid),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentUserUid),
        ),
      ) as String);

  @override
  _i7.Future<String> createOrUpdateConversation(
          _i14.ConversationModel? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateConversation,
          [conversation],
        ),
        returnValue: _i7.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createOrUpdateConversation,
            [conversation],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createOrUpdateConversation,
            [conversation],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Stream<List<_i14.ConversationModel>> getConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [],
        ),
        returnValue: _i7.Stream<List<_i14.ConversationModel>>.empty(),
        returnValueForMissingStub:
            _i7.Stream<List<_i14.ConversationModel>>.empty(),
      ) as _i7.Stream<List<_i14.ConversationModel>>);

  @override
  _i7.Future<String?> checkConversationExistence(List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConversationExistence,
          [userIds],
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> sendMessage(
    _i15.MessageModel? message,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            message,
            conversationId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Stream<List<_i15.MessageModel>> getMessages(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [conversationId],
        ),
        returnValue: _i7.Stream<List<_i15.MessageModel>>.empty(),
        returnValueForMissingStub: _i7.Stream<List<_i15.MessageModel>>.empty(),
      ) as _i7.Stream<List<_i15.MessageModel>>);
}

/// A class which mocks [ChefService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChefService extends _i1.Mock implements _i16.ChefService {
  @override
  _i7.Future<List<_i17.UserModel>> fetchChefDocuments() => (super.noSuchMethod(
        Invocation.method(
          #fetchChefDocuments,
          [],
        ),
        returnValue: _i7.Future<List<_i17.UserModel>>.value(<_i17.UserModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i17.UserModel>>.value(<_i17.UserModel>[]),
      ) as _i7.Future<List<_i17.UserModel>>);
}

/// A class which mocks [DishesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDishesService extends _i1.Mock implements _i18.DishesService {
  @override
  List<_i19.DishModel> get dishes => (super.noSuchMethod(
        Invocation.getter(#dishes),
        returnValue: <_i19.DishModel>[],
        returnValueForMissingStub: <_i19.DishModel>[],
      ) as List<_i19.DishModel>);

  @override
  set dishes(List<_i19.DishModel>? _dishes) => super.noSuchMethod(
        Invocation.setter(
          #dishes,
          _dishes,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<List<_i19.DishModel>> fetchDishes() => (super.noSuchMethod(
        Invocation.method(
          #fetchDishes,
          [],
        ),
        returnValue: _i7.Future<List<_i19.DishModel>>.value(<_i19.DishModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i19.DishModel>>.value(<_i19.DishModel>[]),
      ) as _i7.Future<List<_i19.DishModel>>);
}

/// A class which mocks [UserdataServiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserdataServiceService extends _i1.Mock
    implements _i20.UserdataServiceService {
  @override
  _i7.Future<List<_i17.UserModel>> fetchUsersDocuments() => (super.noSuchMethod(
        Invocation.method(
          #fetchUsersDocuments,
          [],
        ),
        returnValue: _i7.Future<List<_i17.UserModel>>.value(<_i17.UserModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i17.UserModel>>.value(<_i17.UserModel>[]),
      ) as _i7.Future<List<_i17.UserModel>>);

  @override
  _i7.Future<bool> storeUserDetails(
    Map<String, dynamic>? userModel,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserDetails,
          [
            userModel,
            uid,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [CommentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentService extends _i1.Mock implements _i21.CommentService {
  @override
  _i3.UserServices get userService => (super.noSuchMethod(
        Invocation.getter(#userService),
        returnValue: _FakeUserServices_1(
          this,
          Invocation.getter(#userService),
        ),
        returnValueForMissingStub: _FakeUserServices_1(
          this,
          Invocation.getter(#userService),
        ),
      ) as _i3.UserServices);

  @override
  List<_i22.CommentModel> get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: <_i22.CommentModel>[],
        returnValueForMissingStub: <_i22.CommentModel>[],
      ) as List<_i22.CommentModel>);

  @override
  set comments(List<_i22.CommentModel>? _comments) => super.noSuchMethod(
        Invocation.setter(
          #comments,
          _comments,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  dynamic getComments(String? recipeId) => super.noSuchMethod(
        Invocation.method(
          #getComments,
          [recipeId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> addComment(_i22.CommentModel? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [comment],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> addCommentToFirestore(_i22.CommentModel? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCommentToFirestore,
          [comment],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i22.CommentModel>> fetchCommentsByRecipeId(
          String? recipeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCommentsByRecipeId,
          [recipeId],
        ),
        returnValue:
            _i7.Future<List<_i22.CommentModel>>.value(<_i22.CommentModel>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i22.CommentModel>>.value(<_i22.CommentModel>[]),
      ) as _i7.Future<List<_i22.CommentModel>>);

  @override
  _i7.Future<List<String>> uploadImagesToFirebase(List<_i23.File>? images) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImagesToFirebase,
          [images],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SavedRecipeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedRecipeService extends _i1.Mock
    implements _i24.SavedRecipeService {}
